name: CI/CD - DEV

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy-frontend:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT || 22 }}
          SOURCE: "frontend/dist/"
          TARGET: ${{ secrets.DEPLOY_PATH }}
          EXCLUDE: "/node_modules/, /.git/"
          SCRIPT_BEFORE: |
            echo "Preparing deployment..."
          SCRIPT_AFTER: |
            echo "Deployment completed successfully!"
            echo "Restarting services if needed..."
